### ISSUE TITLE
PID recognision

### ISSUE THREAD

**Issue by ColinAnthony** [philliplab/MotifBinner#102]
What happens if the prefix and suffix are detected, but the PID is of a different length to what is expected (deletion/insertion in the PID)? I am assuming that this gets discarded.

**Comment by philliplab** [comment]
I will add a few tests that will look into this

**Comment by philliplab** [comment]
yes they will get discarded.

In very rare situations they will be kept - this is when the distance from the insertion or deletion to the end of the suffix or start of the prefix is less than the maximum allowed mismatches.

For example:
prefix = 'ACGT'
pid = 'AATT'
suf = 'CCG'

if an insertion (of an A) takes place at the end of the pid then the alignment will be
ACGTAATTACCG
ACGTAATTCCG

yielding a mismatch of only 3, so if 4 mismatches were allowed, then this might cause problems. (This will only be a problem in the case of very short suffixes and shows the importance of adjusting max.mismatches allowed to the pre/suf-fix lengths)
