### ISSUE TITLE
Design a way to make the mislabel detector work when the paired end reads do not overlap.

### ISSUE THREAD

**Issue by philliplab** [philliplab/MotifBinner#107]
Currently I have two ideas: (just ideas - feasibility have not been explored)
1) Have a preprocessing step in which gaps are inserted according to hxb2 then replace gaps with N's and make sure that aligning an N to any character does not impose a penalty
2) Compute the distances and make sure that the gap penalties are tuned to values so that putting a large gap in the middle of the sequence does not incur a large penalty

**Comment by ColinAnthony** [comment]
is this necessary.
I join my non overlapping reads prior to binning, but for people who don't want to do this, would it not be better to accept the forward and reverse reads separately and do consensus generation separately?
You could specify which read has the PID and use that to create a list of read names that should go into each bin, then forward and reverse reads get binned according to that list? does this make sense?

**Comment by philliplab** [comment]
It would take a fair amount of work to extend the current version of MotifBinner to be aware of pair-end reads. This will have to wait for a next version.

For now I will keep on thinking about the 2 options originally outlined.

**Comment by philliplab** [comment]
A problem is that the method will not know when the insertion is due to the reads not overlapping and when it is due to an actual deletion from the sequence or an insert in another sequence.

The implication being that if you want to put reads into MotfBinner that do not overlap, then its ability to detect mislabeled sequences where the primary difference is an insert or deletion will be greatly diminished (this was also the primary goal of MotifBinner - to produce cleaner consensus sequences by throwing out mislabeled sequences with indels)

The best solution might be the one @ColinAnthony proposed that uses only non-merged data. However the motif finder will have to be rewritten.

**Comment by ColinAnthony** [comment]
Just to clarify, this is to expand functionality to cases where the user
does not want to join the non overlapping reads prior to binning?
one option would be to join the reads with a character ie: a string of
"!"'s or something , bin them and then split them apart again afterwards?
This should mean we can avoid rewriting the code.
We would need to make sure that "base" to "!' matches are handled correctly
though.

There are programs to do the merging or joining of the reads. I don't think
the binner needs to handle this


On 20 April 2015 at 13:24, Phillip Labuschagne <notifications@github.com>
wrote:

> A problem is that the method will not know when the insertion is due to
> the reads not overlapping and when it is due to an actual deletion from the
> sequence or an insert in another sequence.
>
> The implication being that if you want to put reads into MotfBinner that
> do not overlap, then its ability to detect mislabeled sequences where the
> primary difference is an insert or deletion will be greatly diminished
> (this was also the primary goal of MotifBinner - to produce cleaner
> consensus sequences by throwing out mislabeled sequences with indels)
>
> The best solution might be the one @ColinAnthony
> <https://github.com/ColinAnthony> proposed that uses only non-merged
> data. However the motif finder will have to be rewritten.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/philliplab/MotifBinner/issues/107#issuecomment-94427846>
> .
>



-- 

Colin Anthony, PhD

Postdoctoral Research Fellow
Medical Virology
University of Cape Town
Tel: +27 (0)21 404 7760

**Comment by philliplab** [comment]
The problem is that if there is paired end reads which do not overlap, the mislabel detector will not work correctly.

**Comment by philliplab** [comment]
The design propsed by @ColinAnthony  will be implemented.

remove_motifs need to be extended to also return the sequence_name and their pids.

extract_motifs, extract_motifs_par and extract_motifs_iterative need to be extended to pass along the extra result.

in batch_utilities, process_file must be updated to save the sequence_name / pid data.

Then a new function must be written that assigns pids to sequences based on this file. (pid_from_lookup) Make sure to correctly handle unmatched sequences exactly like extract_motifs

Lastly, process_file must that the seq_name/pid file as an optional argument. If this file is supplied, then the extract motifs step must be skipped and a PID must just be assigned using the new pid_from_lookup function. Make sure to correctly handle unmatched sequences exactly like extract_motifs

**Comment by philliplab** [comment]
moved to bitbucket/trello
