### ISSUE TITLE
Design and test various techniques for removing mislabelled sequences from a bin

### ISSUE THREAD

**Issue by philliplab** [philliplab/MotifBinner#11]
Deciding which sequences in a bin are mislabelled is pretty complicated. We need to spent a solid amount of time to decide on a correct technique. Consider making a vignette about it

**Comment by philliplab** [comment]
Three strategies are implemented. Remove none, remove some at random and the information variance balance.

Now we need some more! To be discussed at our next meeting.

**Comment by MurrayLogan** [comment]
@philliplab - is the information variance balance strategy based on within bin diversity?  I know we plan to implement something  like this to detect mislabelled sequences.. Would you mind refreshing my memory a bit?

**Comment by philliplab** [comment]
This is the description for the method:

#' Finds the outliers in a bin by balancing the amount of information that is
#' lost with the variance reduction that is realized.
#'
#' This approach removes outliers from a bin by finding the sequence with the
#' highest average distance to all other sequences in the bin. It is then
#' removed. The ratio of the reduction in the average distance between the
#' sequences and the reduction in the information available (where the number
#' of DNA sequences in the bin is taken as the measure of the amount of
#' information) is then computed.  The process will continue until either all
#' data has been removed or the ratio drops below some threshold

Colin will also be able to explain it to you.

**Comment by philliplab** [comment]
We decided to rather test how accurate the entire process is (how accurately can we reconstruct the consensus string) than benchmarking intermediate steps
