### ISSUE TITLE
mislabel classification metrics

### ISSUE THREAD

**Issue by philliplab** [philliplab/MotifBinner#12]
A number of metrics must be considered when looking at the accuracy of
classification.

Consider these standard classification metrics:

#### Sensitivity:
Number of true 'in' classifications / (Total size of true 'in' population)

#### Specificity:
Number of true 'out' classifications / (Total size of the 'out' population)

Maximize both simultaneously

Now, in addition to these two, there are other metrics of interest that we can
derive based on our knowledge of the system.

#### Maximum distance in the final dataset: 
We know that the only source of errors
should be the sequencing process. We have access to data about the error rates
of the sequencing process. We can use this to make a statement like:

The sequencing process is accurate to such a degree that no two reads of the
same molecule should differ by more than one base per 100 bases. Build a metric
around this information.

#### Speed

Time take to perform the classification. Can become a big bottleneck

**Comment by philliplab** [comment]
@ColinAnthony @MurrayLogan 

I need some guidance on how to set up the metric that tracks the 'Maximum distance in the final dataset'

Do you think that we can make a statement (based on actual data) like this:
"no two reads of the same molecule should differ by more than one base per 100 bases"
?

**Comment by MurrayLogan** [comment]
@philliplab 

When you mean final dataset, is this after consensus sequence generation and when you say, "no two reads of the same molecule..." does this refer to reads that are tagged with the same PrimerID...?

We will have to take into account how much error correction has been done, as there are a number of processes during sample prep that introduce errors, i.e: not just sequencing. We can then make a statement based on theoretical error rates combined together to calculate expected error.

**Comment by philliplab** [comment]
We are only talking about a single bin here. So the final dataset will be all the sequences we believe to be from a single virus molecule but just before a consensus sequence is generated. So sequences will have the same PrimerID and we would have attempted to throw out mislabelled sequences (sequences that accidentally got the same PrimerID)

"no two reads of the same molecule..." - yes tagged with the same PrimerID since they were binned together.

Ahhh, I see - it is a little more complicated - but in the worst case, we can just pick a number after thinking really hard for a few minutes...

**Comment by ColinAnthony** [comment]
Can we calculate this empirically? And compare to the theoretical value?
Take the correctly binned sequences and calculate the distance from
consensus?

**Comment by MurrayLogan** [comment]
OK, so looking into it a bit more the error rates for reverse transcription and PCR are probably negligible.. I think a 1% error rate for the MiSeq data is probably a good estimate..

I agree with Colin, it would be good to calculate what we see with the theoretical value and compare the two. Would it be possible to generate a consensus and then perform this task on the sequences used to generate the consensus sequences as Colin suggested?

**Comment by philliplab** [comment]
Yes, I am actually working on that right now. However, the problem comes in with data. How do we know that data was correctly binned?

I will create an issue later today or possibly tomorrow in which I start working on the test data. Lets wait for that and then proceed. See #16

**Comment by philliplab** [comment]
I believe that Colin computed this to be 1.9%.

The system is set up so that the metric is just reported and not used as an optimization criteria - so I will close this issue now.
