### ISSUE TITLE
Create test data for the mislabel detector

### ISSUE THREAD

**Issue by philliplab** [philliplab/MotifBinner#16]
We need to create a whole bunch of test bins that we can use to check how well the classifiers are performing.

I am opting for just hard coding the test data into the package.

First example:
'test1' = list('src' = DNAStringSet(c('AAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
                                               'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
                           'out' = DNAStringSet('CCCCCCCCCCCCCCCCCCCCCCCCCCCCC')
                           )

@ColinAnthony  @MurrayLogan 
What I will need is more example data. How do you think we should go about getting test data?

Should I give you a couple of bins and then you classify them by hand?

What I have in mind is to give you a bunch of FASTA files, each file containing a single bin.

I will set the headers to 'seqx' (see below) for each sequence and I will sort the FASTA files so that identical sequences occur below each other. Then you need to set sequence name to 'out' for each sequence you think should not belong to the bin?

x will range from 1 to the number of unique sequences in the bin. So the sequences will be for example:
seq1, seq1, seq1, seq1, seq2, seq3, seq4, seq5, seq5, ....

Do you think this will work? Alternative ideas for producing test data? Please note that we should be able to put this data on the internet, so no confidential data. But I think that putting just a few of Colin's bins on the internet will not do too much damage?

**Comment by philliplab** [comment]
@ColinAnthony @MurrayLogan 

After a gnashing of teeth I have a couple of 'test' data sets. However, I think we might want to be stricter with what we keep in ('src') or throw out ('out'). What do you guys think? Please feel free to modify the files. I will email them to you as soon as I finish this comment.

@ColinAnthony do you think we can put that data on the internet? In their current format, they are just little piece of the HIV genome with no idea of where they come from.

**Comment by ColinAnthony** [comment]
HI,
Yes, I can do this...
People could blast the sequences and identify the patient and gene region
that way. but with just a few sequences with no time point identifiers, it
should be ok...what is the reason for putting on the internet? as a built
in testing component of the tool?

On 12 January 2015 at 10:29, Phillip Labuschagne <notifications@github.com>
wrote:

> @ColinAnthony <https://github.com/ColinAnthony> @MurrayLogan
> <https://github.com/MurrayLogan>
>
> After a gnashing of teeth I have a couple of 'test' data sets. However, I
> think we might want to be stricter with what we keep in ('src') or throw
> out ('out'). What do you guys think? Please feel free to modify the files.
> I will email them to you as soon as I finish this comment.
>
> @ColinAnthony <https://github.com/ColinAnthony> do you think we can put
> that data on the internet? In their current format, they are just little
> piece of the HIV genome with no idea of where they come from.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/philliplab/MotifBinner/issues/16#issuecomment-69539961>
> .
>



-- 

Dr. Colin Anthony, PhD

Postdoctoral Research Fellow
Medical Virology
University of Cape Town

**Comment by philliplab** [comment]
It would be for testing purposes only - It is very inconvenient to have to distribute test data separately from the package. An alternative would be to use data from the internet or simulating data.
