### ISSUE TITLE
Note the weirdness with the way the thresholds on the infovar balance method works.

### ISSUE THREAD

**Issue by philliplab** [philliplab/MotifBinner#34]
bin <- DNAStringSet(c(rep('AAAAA', 5), rep('AAAAC', 10),
                        rep('AAAAG', 2), rep('TTTTT', 1)))
  classified <- classify_bin_infovar_balance(bin, threshold=1)

vs

bin <- DNAStringSet(c(rep('AAAAA', 5), rep('AAAAC', 10),
                        rep('AAAAG', 2), rep('AATTT', 1)))
  classified <- classify_bin_infovar_balance(bin, threshold = 1, start_threshold = 0.5)

yields very different answers. Is this a reason to stop with the relative thresholds and shift back to absolute thresholds?

**Comment by philliplab** [comment]
Consider the bin:
c(rep('AAAAA', 5), rep('AAAAC', 10),
rep('AAAAG', 2), rep('TTTTT', 1))

and the bin
c(rep('AAAAA', 5), rep('AAAAC', 10),
rep('AAAAG', 2), rep('AATTT', 1))

Note how the last sequence differs: TTTTT vs AATTT

The result produced from running the same code on these two bins varies:

In bin 1, only the sequence TTTTT is removed

In bin 2, only the sequences AAAAA is left in the bin.

This behaviour is a function of the relative way in which the threshold is computed. The average distances in the first bin is much higher than in the second bin, leading to the difference in decisions. 

@ColinAnthony  Is this acceptable or should the method be tweaked to work with absolute threshold rather? Instead of looking at how much data is lost relative to how much the variance is reduced, should we look at what the per site read error rate would have had to be to produce this bin?

**Comment by ColinAnthony** [comment]
In bin 1, we get a degenerate consensus out AAAAN.
This is preferred to the Bin 2, where we get AAAAA, but have no way of knowing whether AAAAG/T/C was actually the correct sequence.
I will end up filtering out AAAAN in my analysis, but for other work this will not be necessary.

In summary: Bin 1 ftw.

**Comment by ColinAnthony** [comment]
In a bin like this, it will not be possible to avoid getting a degenerate base. This is ok. So long as we are minimizing the number of such cases to those where removing mislabeled, outlying sequences cannot rescue the bin.

**Comment by philliplab** [comment]
This behaviour is not ideal, but it will always be a part of the information variance balance technique. The correct way to address it is to create a new mislabel detector based on absolute thresholds
