### ISSUE TITLE
Get some clarification on how the consensus string creator should behave.

### ISSUE THREAD

**Issue by philliplab** [philliplab/MotifBinner#37]
What is the consensus of AA, AA, AC. It is AA or AN? In other words what is the thresholds that must be met before a letter is placed in consensus?

**Comment by ColinAnthony** [comment]
Hi, Here is the full degeneracy code breakdown
http://en.wikipedia.org/wiki/Nucleic_acid_notation

We have previously set the threshold at 50%...or where there is an equal distribution if there are multiple variants at a site.

**Comment by philliplab** [comment]
## How does the consensusString Function in Biostrings actually work?

When and how does ambigueity characters get added to the data. Should I write
my own version of the function to deal with it?

### It behaves as expected for matching sequences

```r
consensusString(DNAStringSet(c('AAA', 'AAA')))
```

```
## [1] "AAA"
```

```r
consensusString(DNAStringSet(c('ACGT', 'ACGT')))
```

```
## [1] "ACGT"
```

### For mismatches - a very strict threshold must be met

```r
consensusString(DNAStringSet(c('AAC', 'AAA')))
```

```
## [1] "AAM"
```

```r
consensusString(DNAStringSet(c('AAC', 'AAA', 'AAA')))
```

```
## [1] "AAM"
```

```r
consensusString(DNAStringSet(c('AAC', 'AAA', 'AAA', 'AAA')))
```

```
## [1] "AAM"
```


```r
consensusString(DNAStringSet(c('AAC', 'AAA', 'AAA', 'AAA', 'AAA')))
```

```
## [1] "AAA"
```

```r
consensusString(DNAStringSet(c('AAC', 'AAT', 'AAA', 'AAA', 'AAA', 'AAA')))
```

```
## [1] "AAA"
```

### Can this threshold be lowered?

```r
consensusString(DNAStringSet(c('AAC', 'AAA')), threshold = 0.5)
```

```
## Error in .local(x, ...): 'threshold' must be a numeric in (0, 1/sum(nchar(ambiguityMap) == 1)]
```

No because they are using some strange restrictions. Specifically the threshold is that no other character may occur more than 25% of the time. This is stricter than the current behaviour. Is this a problem or can the stricter behaviour be used?

If you want to use the 50% criteria again, then I would have to either write my own consensusString generator or modify theirs - it might take a bit of time.

I think it would probably be better to reduce that restriction because what this means is that any bin with 2, 3 or 4 sequences that are not identical will have degeneracy (unless the sequences with mismatches were removed by the outlier detector)
