### ISSUE TITLE
Explore writing a custom consensus sequence constructor

### ISSUE THREAD

**Issue by philliplab** [philliplab/MotifBinner#38]
The availability of consensusMatrix might make it easy

**Comment by philliplab** [comment]
So it turns out to be really easy to write a consensus string function as long as the threshold is greater than 0.5. This will be implemented as an alternative, however if the threshold should be allowed to go below 0.4, then extra code will be needed to handle ties.

@ColinAnthony  @MurrayLogan will you guys ever want a threshold below 0.5?

**Comment by philliplab** [comment]
What is the consensus of
c('AAAAAAAAAAA','AAAAAAAAAAA','AAAAAAAAAAA',
'AAAAAAAAAAC','AAAAAAAAAAG','AAAAAAAAAAT')
?

According to the 50% rule it should be an ambiguity character, but according to the rule Biostrings use, it is A.

@ColinAnthony @MurrayLogan  are you guys happy to have a two step system that works like this:
1) Test if a letter occurs more than 50% of the time. If there is such a character, then that character goes into the consensus string.
2) If there is not such a character, then find all letters that occur in more than 25% of the sequences and construct an ambiguity character from them.

Point 2 is potentially dodgy - an alternative can be to just construct an ambiguity character from all the unique letters that occur at that position. But this is also a little dodgy - so which of the two evils do you prefer? The current implementation uses the 25% threshold to select letters for the ambiguity character.

**Comment by ColinAnthony** [comment]
I would perhaps suggest a simple majority rule where the most frequent sequence gets used...and where there is no majority, a degeneracy code is used.
