### ISSUE TITLE
make mostConsensusString play nice with gaps

### ISSUE THREAD

**Issue by philliplab** [philliplab/MotifBinner#44]

**Comment by philliplab** [comment]
There are no ambiguity characters for dealing with gaps. How should I handle gaps?

Two options:
If the set of letters that occur most frequently contains gaps, then

1) remove the gap character and build an ambiguity character  from the remaining characters

2) put a gap

example:
AAA; AAA; AA-; AA-

For third position, should the methof make a gap character or an A?

@ColinAnthony please advise

**Comment by ColinAnthony** [comment]
AAAAAAaa!
This is what killed us last time.
incorrect handling here will introduce frame shift mutations.
If this happens in a homopolymer region...it doesnt matter which is kept, the base or the gap. after I have aligned all consensus sequences it is very easy to correct this.
For non-homopolymers, it is a problem.
This is where we are hoping the mislabelled sequences removal option will reduce the occurrence of this problem.
...how about we use an '!' to flag these?
the homopolymers can then be corrected and the other ones discarded...we might need to make sure that the aligners will tolerate the symbol that we use though. but I think ! should be accepted.

**Comment by philliplab** [comment]
I am going to use + cause that is what Biostrings uses to fill in the gaps. If that causes problems for the aligners, then we can change it at a later stage.

**Comment by philliplab** [comment]
@ColinAnthony please confirm that the following behaviour is desired:

1) A, A, A, A yields A
2) A, A, A, - yields A
3) A, A, -, - yields +
4) A, -, -, - yields -
