### ISSUE TITLE
meet with Simon/Colin to discuss implications of bin size on expected max distance in the bin

### ISSUE THREAD

**Issue by philliplab** [philliplab/MotifBinner#57]

**Comment by ColinAnthony** [comment]
I'm guessing there's a likelihood of distance distribution, so by chance you may get some higher distances in larger bins. We can check empirically whether the larger bins have higher 'mislabelled' seq rates ...which would obviously produce higher distances for larger bins

**Comment by philliplab** [comment]
This can be computes analytically using order statistics. I have done some computations and there are pretty significant effects. Will be really hard to communicate this via email so we need to meet.

**Comment by philliplab** [comment]
Also look at the unprocessed bin report and see how to go about identifying cutoffs for the mislabel classifier from there

**Comment by philliplab** [comment]
Need to decide which metrics to report in a summarized csv file that reports on the process
